g3/config.py, g3/main.py, poetry.lock, pyproject.toml, tests/test_config.py
A new `Config` class has been added to handle reading and writing to a configuration file. This class is used in the main application to prompt the user for configuration details. The `faker` package has been added as a dependency for testing purposes. New tests have been added to verify the functionality of the `Config` class.
Closes #3, closes #4
=> Add configuration management and tests

g3/main.py
Take advantage of `rich` to make the `configure` flow a bit more pleasant and intuitive. Also, switched from `typer` prompt to rich `Prompt` which supports predefined lists of choices, helping the user provide proper values.
=> Revamp styling for g3 configure

.github/publish_to_jfrog.yml
Add the skeleton yml file for publishing to JFrog.
Required to have actions available for further tweaking.
=> Add yaml for publishing

.github/workflows/publish_to_jfrog.yml
- Workflows must be placed in the correct folder
- Fix indentation for tags
=> Move workflow to the correct directory

.github/workflows/publish_to_jfrog.yml
- Add env variables to accurately pull the respective credentials
=> Credential reference from variable and secret

g3/git/data.py, g3/git/diff.py, g3/git/shell.py, tests/git/test_diff.py, tests/git/test_shell.py
Returns git info to be used with the model
Example
```python
ModelData(
filenames=['g3/git/data.py', 'g3/git/git.py'],
diffs=[
Diff(
filename='g3/git/data.py',
patch='diff --git a/g3/git/data.py b/g3/git/data.py\nnew file mode 100644\nindex 0000000..3cd7cd5\n--- /dev/null\n+++ b/g3/git/data.py\n@@ -0,0 +1,22 @@\n+from dataclasses import
dataclass\n+from typing import List\n+from g3.git.diff import Diff, get_filenames, get_files_changed\n+from g3.git.shell import Shell\n+@dataclass\n+class ModelData:\n+    filenames: List[str]\n+
diffs: List[Diff]\n+    repo_name: str\n+    branch_name: str\n+\n+\n+def get_data_for_model() -> ModelData:\n+    sh = Shell()\n+    assert sh.is_git()\n+\n+    return ModelData(\n+
filenames=get_filenames(sh),\n+        diffs=[diff for diff in …
```
=> Adds git diff and function to return data for the model

g3/config/handler.py, g3/config/openai.py, g3/generate/client.py, g3/generate/preview/cli.py, g3/generate/prompts/commit/creator.py, g3/generate/prompts/commit/examples/node.py, g3/generate/prompts/commit/examples/python.py, g3/generate/prompts/commit/examples/ruby.py, g3/git/shell.py, g3/main.py, tests/config/test_path.py
Fixes linter's warnings after running:
```
poetry run pre-commit run --all-files
```
=> FIX: Linter warnings

.github/workflows/publish_to_jfrog.yml, pyproject.toml
- Add poetry plugin to pull number from git tag
- Move items to step
=> Version numbering and secret move to step

g3/config/exclude.py, g3/git/diff.py, tests/git/test_diff.py
Adds a list of file to exclude from model data
Closes #21
=> adds excluded files

.github/workflows/publish_to_jfrog.yml
A plugin has been introduced to allow for proper tagging. A new tag will be required to have this functionality available after pushing to main.
=> Breaking change for tagging

g3/generate/preview/cli.py
This PR adds markdown preview of messages
Please include a summary of the proposal, relevant motivation and context.
Closes issue \#1
=> Adds support for previewing markdown messages

.github/workflows/publish_to_jfrog.yml
- Add the correct plugin for tagging
- Add the distinction for building the main branch and tags
- Add the ability to build custom branch with custom tag when running the workflow manually
=> Plugin addition and workflow conditional running

g3/git/client.py
Adds commit command to `git` client
Closes issue \#1
=> adds commit to git client

.github/workflows/publish_to_jfrog.yml
As the main tag exists, use the short hash to create unique builds.
=> Unique main branch build through short hash

.github/workflows/publish_to_jfrog.yml
- Remove main branch build
- Add default values for manual builds as a safeguard
=> Remove main branch build

.github/workflows/publish_to_jfrog.yml
Cleanup run condition for main branch to avoid empty runs
=> Remove run condition from main branch

.github/workflows/test.yml
=> Add testing on Pull Request

g3/generate/commit/messages/creator.py, g3/generate/pr/messages/creator.py, g3/generate/preview/cli.py, g3/github/client.py, g3/main.py
- Refactored message generation logic in `commit/messages/creator.py` and `pr/messages/creator.py`
- Replaced `display_selection` with `Presenter` class in `preview/cli.py`
- Updated `open_pull_request` method in `github/client.py` to return `PullRequest` object
- Improved user feedback during message generation in `main.py`
=> Refactor message generation and presentation logic

g3/generate/commit/messages/creator.py, g3/generate/commit/prompts/creator.py, g3/generate/preview/cli.py, g3/git/gitinfo.py, g3/github/client.py, g3/main.py, poetry.lock, pyproject.toml
• Added functionality to compare original and generated commit messages                                                                                                                                                                                     
• Modified the Creator class to accept an optional commit parameter                                                                                                                                                                                         
• Added a new display_comparison function to compare original and generated messages                                                                                                                                                                        
• Updated GitInfo class to handle commit …
=> Add support for comparing original and generated commit messages

g3/git/client.py, g3/git/gitinfo.py
- Added a new function `get_commit_messages` in `client.py` to fetch commit messages between two branches.
- The function uses `merge-base` and `rev-list` git commands to fetch the commit messages.
Please include a summary of the proposal, relevant motivation and context.
Closes issue \#1
=> Add get_commit_messages function in client.py

g3/generate/commit/prompts/creator.py, g3/generate/commit/prompts/examples/node.py, g3/generate/commit/prompts/examples/python.py, g3/generate/pr/prompts/creator.py, g3/generate/preview/cli.py, g3/git/client.py, g3/git/gitinfo.py, g3/main.py
Various formatting and typing fixes
=> Add fixes from pre-commit

g3/generate/client.py, g3/generate/commit/messages/creator.py, g3/generate/pr/messages/creator.py, g3/generate/preview/cli.py
Please include a summary of the proposal, relevant motivation and context.
=> Add streaming support

g3/config/handler.py, g3/main.py, pyproject.toml
This pull request includes a refactor of the configuration handling and user prompts in the g3 repository. 
The changes aim to improve the user experience during configuration setup and to handle default values more efficiently. 
Minor lint fixes were also made.
- Refactored the configuration handling in `handler.py` to return 0 instead of None for temperature if not set.
- Replaced the usage of `Prompt` with `inquirer` in `main.py` for a more interactive user experience.
- Updated the configuration setup process to use `inquirer` for user prompts.
- Minor lint fixes were made.
=> Refactor Configuration Handling

g3/config/openai.py, g3/generate/pr/prompts/creator.py, g3/git/gitinfo.py, g3/github/github_info.py
Fixes origin branch name for get_commit_messages.
=> Add fix for origin branch name

g3/config/handler.py, g3/generate/pr/prompts/creator.py, g3/git/gitinfo.py, g3/main.py, tests/git/test_diff.py
- Added `message_tone` property to `ConfigHandler` in `g3/config/handler.py` to handle message tone configuration
- Modified `Creator` class in `g3/generate/pr/prompts/creator.py` to use the updated configuration
- Updated `GitInfo` class in `g3/git/gitinfo.py` to improve handling of git information
- Adjusted `commit` function in `g3/main.py` to use the new `message_tone` configuration
- Refactored `test_diff.py` to improve test structure and readability
=> Update configuration handling and improve test structure

README.md, g3/generate/pr/messages/creator.py, g3/github/github_info.py
This pull request introduces a new section in the README.md file. 
The new section provides detailed installation instructions for the tool. 
It also includes steps on how to configure the tool with Github token and open-ai key.
- Added a new section for installation instructions in README.md
- Included steps to configure the tool with Github token and open-ai key
Please review and provide your feedback.
=> Update README with Installation Instructions

pyproject.toml
This pull request updates the authors list in the pyproject.toml file. 
The update is necessary to reflect the contributions of all team members to the project.
- Added all authors to the authors list in pyproject.toml
Please review and let me know if there are any issues or concerns.
=> Update authors list in pyproject.toml

g3/generate/pr/messages/creator.py, g3/generate/pr/prompts/creator.py, g3/generate/preview/cli.py, g3/github/client.py, g3/github/github_info.py, g3/main.py
This pull request includes a series of updates and refactoring to the pull request creation and editing methods. 
The changes aim to improve the PR handling and message presentation. 
Additionally, the default branch in PR message creator has been updated. 
- Refactored pull request creation and update methods
- Added support for PR editing
- Updated PR handling and message presentation
- Replaced generate method with stream
- Updated default branch in PR message creator
- Enhanced PR editing functionality
Please review the changes and provide your feedback.
=> Refactor and Update Pull Request Creation and Editing Methods

README.md
This pull request updates the README file of the g3 repository. 
The configuration section has been expanded with detailed instructions. 
Additionally, usage instructions for `g3 commit` and `g3 pr` commands have been added. 
- Expanded the configuration section in README.md
- Added instructions for entering Github token, open-ai key, openai model, temperature, openai api version, tone, commit message max characters, and PR description max words
- Added usage instructions for `g3 commit` and `g3 pr` commands
- Included options for each command
- PRD-1234
=> Update README with Detailed Configuration and Usage Instructions

g3/generate/commit/prompts/creator.py
=> Change commit prompt to dissallow branch name and some formatting.

g3/generate/commit/prompts/creator.py
- Modified the token limit exception handling in the `create` method of the `Creator` class.
- Instead of directly raising the `TokenLimitExceededException`, the exception is now assigned to a variable and printed.
- The program will now exit with a status code of 1 when the token limit is exceeded. This change provides a more user-friendly error message and a clear exit point when the token limit is exceeded.
Please include a summary of the proposal, relevant motivation and context.
Closes issue \#1
=> Update token limit exception handling in Creator class

g3/generate/commit/prompts/creator.py, g3/generate/pr/messages/creator.py, g3/generate/pr/prompts/creator.py, pyproject.toml
This pull request includes a series of changes to the PR message creator in the g3 project. The main focus was on refactoring the code for better readability and adding new functionality. Additionally, the version number in pyproject.toml was updated for the new release.
- Refactored the way Jira tickets are included in commit and PR prompts.
- Removed unnecessary code in `creator.py` files to improve readability.
- Fixed inconsistencies in the use of markdown syntax.
- Added GitInfo to the Creator class in `g3/generate/pr/messages/creator.py`.
- Implemented push functionality to update and create pull requests.
- Updated the version number in pyproject.toml from 0.4.0 to 0.4.1.
- PROD-1
cc @ikarachristos
=> Refactor and Enhance PR Message

README.md
This pull request updates the README file with detailed instructions for installing and configuring the G3 CLI tool. It also includes a comprehensive guide for contributors, detailing how to set up a development environment and enable pre-commit hooks. The Python version requirement for the project has been updated to 3.11, and information on using Poetry for dependency management has been added.
- Added detailed installation instructions for the G3 CLI tool
- Included a new section on how to configure the tool
- Added a comprehensive guide on how to contribute to the project, including setting up a development environment and enabling pre-commit hooks
- Updated the project's Python version requirement to 3.11
- Added information on how to use Poetry for dependency management
Closes #2
=> Update README with Installation and Development Instructions

.github/workflows/publish_to_jfrog_and_pypi.yml, Makefile
- Add the ability to publish to PyPI via poetry
- Add the respective secret (pending deposition) for PyPI
- Rename workflow for better accuracy
Closes issue #101
=> Modify makefile and publish workflow

g3/services/generate/commit/prompts/creator.py, g3/services/generate/pr/prompts/creator.py, g3/services/generate/pr/prompts/template.py
This pull request includes changes to the way prompts are created in commit and PR generators. 
A typo in the PR template has been fixed. 
Unnecessary details about branch and repository from prompts have been removed.
- Refactored the way prompts are created in commit and PR generators
- Fixed typo in PR template
- Removed unnecessary details about branch and repository from prompts
=> Refactor Prompts Creation in Commit and PR Generators

g3/services/generate/commit/prompts/creator.py, g3/services/generate/pr/prompts/creator.py, g3/services/generate/pr/prompts/template.py
This pull request includes a series of updates and refactors to the pull request prompts creation and template. The changes aim to improve the logic of creating prompts, simplify the PR template, and enhance the inclusion of Jira tickets in the PR description.
- Refactored the PR prompts creation logic
- Updated the PR template structure for simplicity
- Improved the method for creating pull request messages
- Enhanced Jira ticket inclusion in pull request descriptions
- Removed branch and repository name from prompts
=> Refactor Pull Request and Commit Message Creation Process

.github/workflows/publish_to_jfrog_and_pypi.yml
- Renames the workflow description to more accurately reflect its function
=> Rename publish workflow

.github/workflows/test.yml
- Add slack notifications for CI results
Closes #114
=> Add slack notification for Pull Request

.github/workflows/payloads/pr_payload.json, .github/workflows/payloads/push_payload.json, .github/workflows/payloads/release_payload.json, .github/workflows/publish_to_jfrog_and_pypi.yml, .github/workflows/test.yml
- Add event-specific steps for extracting information
- Add event-specific notifications
- Add payloads for all cases
Closes issue #123
=> Modify workflows for better reporting

.github/workflows/test.yml
The PR makes the following changes:
- Adds slight modifications to the PR events, excluding the notification from being sent on PR closure as unneeded.
- Slightly simplifies the execution condition for the push event.
Closes issue #123
=> Condition clarification and minor cleanup
